### ISSUE TITLE
The registerChromeUrl() example should discuss style, skin and overlay entries

### ISSUE THREAD

**Issue by eyalroz** [thundernest/addon-developer-support#1]
The [section](https://github.com/thundernest/addon-developer-support/wiki/WindowListener-API:-Getting-Started#windowlistenerregisterchromeurl) regarding `WindowListener.registerChromeUrl()`  has the code for an example call, but only registers "content" and "locale" entries. Is it the case that "style" and "overlay" entries should _not_ be included?  That needs to be stated explicitly.

There's an earlier statement saying that "skin" needs to be replaced by "content" - but it doesn't say how to do that. So, it would also help if this example of a `registerChromeUrl()` call had such a replaced entry.

**Comment by jobisoft** [comment]
I will add an explanation on how to replace resource and skin entries in chrome.manifest. For skin you move the skin folder into your content folder and change all affected URLs in your code to use the content folder. 

Regarding content and locale entries in registerChromeUrls: I could add "only" to the introduction in the first sentence, is that what you mean? Otherwise it says already that you have to register your content and locale entries there.

Since you should no longer have skin or resource entries when you are at the point you use registerChromeUrls, I cannot show the replacement of those entries there. They are already gone.

Does that answer your question?

**Comment by eyalroz** [comment]
> For skin you move the skin folder into your content folder and change all affected URLs in your code to use the chrome://something/content/skin/ URL.

What about the skin-name component of the path? Does that go away? No skinning anymore? TBH, I only ever supported multiple skins on Seamonkey, so I only have a skin folder for classic, but still.

> Since you should no longer have skin or resource entries when you are at the point you use registerChromeUrls, I cannot show the replacement of those entries there. They are already gone.

You can show something pointing to `chrome://something/content/skin/`, and a comment above it saying "this was a skin entry" and another comment line showing what the original skin entry looked like. A little more verbose but clearer.

**Comment by jobisoft** [comment]
> You can show something pointing to chrome://something/content/skin/, and a comment above it saying "this was a skin entry" and another comment line showing what the original skin entry looked like. A little more verbose but clearer.

Good point, will do that.

Regarding skins: I have not done a lot of research here, as I have not found many AddOns really using any skin features, besides a URL different from the content URL. If you start missing something, we got to work on that.

**Comment by eyalroz** [comment]
So, apparently there are quite a bunch of "skin/theme" add-ons:

https://addons.thunderbird.net/en-US/thunderbird/complete-themes/

but I don't know whether there are other add-ons which cater to multiple skins. Also, all those skins seem not to have been updated for TB 78 even.

**Comment by jobisoft** [comment]
I made changes, which I think cover your remarks.

**Comment by jobisoft** [comment]
Closing this to have it out of the way. Reopen, if needed.
