### ISSUE TITLE
The options_ui entry in manifest.json - mentioned without explanation

### ISSUE THREAD

**Issue by eyalroz** [thundernest/addon-developer-support#4]
Apparently, we can spare ourselves the hassle of [this section](https://github.com/thundernest/addon-developer-support/wiki/WindowListener-API:-Getting-Started#windowlistenerregisteroptionspage) is we have an `"options_ui"` entry in `manifest.json`. 

So:

1. Why even have this section to begin with? Just tell us to use `"options_ui"`.
2. There's no explanation of how to add an `"options_ui"` entry , nor an example of a `manifest.json` file with it. A link [here](https://developer.thunderbird.net/add-ons/updating/tb68/overlays) might do the trick.

**Comment by jobisoft** [comment]
Please help me to understand how you could get to any of what you are stating here from what I have written.

Where did I tell you to use option_ui?

I said: If your options page was defined in the removed legacy entry in your manifest.json file, register it via a call to registerOptionPage().

This is a 1-to-1 replacement and will get your XUL optionspage working again.

I could use re-register instead of register to emphasize that.

I only added the note about option_ui so that developers who have switched from a legacy XUL optionpage to a WX HTML option page (via option_ui) already, know, that they of course can continue to use that and do not need to use registerOptionPage(). I do not need to explain how to use option_ui, as that is exactly what I want to save the developer from, as that also requires 
* convert XUL to HTML
* use local storage or experiments to access prefBranch

This will be done in a later update tutorial.

**Comment by eyalroz** [comment]
> Please help me to understand how you could get to any of what you are stating here from what I have written.
> 
> Where did I tell you to use option_ui?

In this sentence at the link (emphasis mine):

> *Note: **Not needed** if your add-on is already using the new options_ui entry in the manifest.json file.*

**Comment by jobisoft** [comment]
I removed it.
