### ISSUE TITLE
[API] NotificationBox

### ISSUE THREAD

**Issue by jobisoft** [thundernest/addon-developer-support#47]
1) The API requires a windowId to identify the window, where the notificationbox should be added. The getNotificationBox function still tries all different known notification boxes, I think with the windowId we can get the type and just use the correct one. We should also add code to create a new notificationbox, if there is none.

2) The priority is currently an integer between 1 and 9, corresponding to internal priority levels. How about just using a color code?

3) The following events are supported:
* onButtonClicked : When a button is clicked, returns notificationId and buttonId. If a registered listener returns true, the notification bar will not be closed.
* onDismissed : When the user hits the "x" of the notification, returns notificationId.
* onClosed : When a notification is closed, returns notificationId. Is triggered either by
  * button
  * dismissal
  * manually calling remove()
  * api shutdown (window close or whatever)

**Comment by benbucksch** [comment]
We need 2 additional features for our use:
* placement at the top (between TB toolbar and folder/message pane)
* setting the background color to a custom color
We'd be happy to contribute it.

**Comment by jobisoft** [comment]
I had a chat with Geoff about this and he thinks colors is also better. Would you drop the priority then altogether? What would it used for, stacking order?

**Comment by jobisoft** [comment]
If you have something, I will not say no to a PR.

**Comment by benbucksch** [comment]
I think priority is very useful and makes sense. It's semantical and allows themes to determine the specific color for a priority. Most use cases will want to use the priority.

We just have some very specific use cases where we need to set a specific color, e.g. for branding.

**Comment by benbucksch** [comment]
We've pushed a few PRs:
* [Bug fixes](https://github.com/jobisoft/notificationBox-API/pull/3)
* [Constants for priority](https://github.com/jobisoft/notificationBox-API/pull/2)
* [CSS for colors](https://github.com/jobisoft/notificationBox-API/pull/5)
* [Placement at top](https://github.com/jobisoft/notificationBox-API/pull/6)
* [Security considerations](https://github.com/jobisoft/notificationBox-API/issues/4)

**Comment by jobisoft** [comment]
@benbucksch and @NeilRashbrook thanks a lot for your input. Merged two of them already.

I just learned the hard way that one of my ideas did not work out: Having this conversation not in the same repository as where the API is living was a stupid idea. I will probably move back. Sorry for theses hickups.

I merged the PR regarding the position of the notification box. I was trying to get my head around something related:
Should we not always create our own notification box area, even for the bottom case? We currently check if one of TBs built-in areas can be found in the window and use it. I would like to be independent of those and just check for our own and use

```
w.gExtensionNotificationTopBox
w.gExtensionNotificationBottomBox
```

What do you think?

**Comment by NeilRashbrook** [comment]
I think it might be confusing to have multiple notification boxes in the same place.

While we're discussing the API, I noticed that you have to be very careful to `return true;` in all of your button event handlers to avoid accidentally closing another notification. Would it make more sense to have a value that opts in to closing the notification? (This is less of a problem for chrome code because it only ever has one listener per button.)

**Comment by benbucksch** [comment]
I think it adds no value to separate the boxes, because you can fix the API implementation at the same time with the TB changes, given that the API will be shipped with TB.
It actually makes things more difficult, because you want notifications to be ordered by priority, not their origin. With 2 boxes, it's almost impossible to do that.

**Comment by benbucksch** [comment]
> you have to be very careful to `return true;` in all of your button event handlers to avoid accidentally closing another notification. 

To clarify: If the button event handler is missing `return true;`, all notifications of that addon will close. That's almost never what we want, so I think it would be good to fix that.

Personally, I would not close by default. Maybe an explicit `return false;` could close it, but I'd actually prefer the even more explicit `bar.close()` when reading the extension code.

**Comment by benbucksch** [comment]
> you have to be very careful to `return true;` in all of your button event handlers to avoid accidentally closing another notification. 

To clarify: If **any** of my button event handlers is missing `return true;`, then the notification bar (on which button the user clicked) will close. So, if I have 2 notifications bars, and bar A should close on button click, and I'm omitting `return true;` in its button handler, and bar B should not close, and I do add `return true;` in its button handler, then the notification bar will _nonetheless_ close, because the handler for bar A also executes and messes me up. This is going to lead to significant hair loss for many addon developers.

Personally, I would not close by default. I'd make an explicit `bar.close()`. This is not only safer, but also easier to read and understand when reading the extension code than a `return false;`, which could mean anything.

**Comment by jobisoft** [comment]
As I mentioned before, this issue is out of place. I still have to find how this can work best. Currently:
 - [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1674002): General status tracking
 - [topicbox](https://thunderbird.topicbox.com/groups/addons/T576f843ea846049c-M2b3bf1c77ba25dfb1d78e7d4/notification-api-proposal): Announcement and discussion with the broader add-on community
 - [google doc](https://docs.google.com/document/d/1mTwVozOiEcDCw3QQKxVz-N5yHY8SVFC9KUL4_x0IN68/): In-depth API discussion
 - [github repo](https://github.com/jobisoft/notificationbar-API): Alternative in-depth API discussion

The [security issue](https://github.com/jobisoft/notificationbar-API/issues/4) is still open and I have made some remarks. I would be very thankful, if you could have a look.
