### ISSUE TITLE
LegacyMenu: accelerator not working?

### ISSUE THREAD

**Issue by opto** [thundernest/addon-developer-support#57]
I tried C, as in the example, and k, and would expect alt-C to open the menuitem (tried in top level next to help menu), but nothing happens. Whereas alt-D(atei) opens the file menu.

Klaus

**Comment by jobisoft** [comment]
Access keys in submenus are triggered by Shift and this is what this API is about (for example placing menu items in tools or file menu).

I have no idea what is wrong when used to add a top level menu. Maybe Alt has to be used because there is no menu open at all, but for why the other ones work with ALT, I do not know. The Shift combination is probably consumed by some other listener in the window, whereas those window listeners do not interfere, once a menu is open.

If you find a fix, a pull request would be great. Closing this, as top level menus is not the intended use.
