### ISSUE TITLE
${namespace} vagueness

### ISSUE THREAD

**Issue by eyalroz** [thundernest/addon-developer-support#8]
This section says:

> `namespace`: The unique name of the wrapper object your script is being loaded into. If a call to any of your functions originates from the global window scope, like on* handlers in your XUL fragments or callbacks and similar function calls, these calls need to have the full function signature, which includes the name of the injected wrapper object: window[namespace].*

But what is this namespace? Is it not simply the "short name" of the extension?

* If it is - where do we tell the WindowListener to use that short name? Or does it figure it out on its own somehow? e.g. based on the "content" chrome element? But then - what if there's more than one of those?
* If it isn't - why? And what is its value?

Later on, in a script, I see:
```
oncommand="window.${namespace}.QuickFolders
```
why isn't it just 
```
oncommand="window.QuickFolders
```
i.e. why isn't QuickFolders the namespace?

**Comment by jobisoft** [comment]
The namespace value is autogenerated and looks like AddOnNSXY with XY being an integer. I cannot let the developer select a name, because that would not guarantee uniqueness. The namespace may change between restarts. You do not need to know it's actual value. You can and should always use the namespace variable.

**Comment by eyalroz** [comment]
> I cannot let the developer select a name, because that would not guarantee uniqueness. 

Disagree. Each extension has its own content entry (well, an extension that uses the WindowListener anyway); and if those weren't unique in name, then all of the chrome:// URIs would get messed up in TB 68.x and earlier as well. So, it _is_ safeto assume those are unique. No need to be "more chaste than the pope", so to speak. And - it would make our extension code clearer, more stable and easier to debug.

> You can and should always use the namespace variable.

But I want to be able to put my XUL in a .XUL file, and not use back-ticks.

And again, I believe it would be simpler and more robust to just choose the extension's short name as the namespace.

**Comment by jobisoft** [comment]
If two AddOns define the same chrome URLs, than the situation is messed up. 

Of course the scope of the experiments of different AddOns are seperated, but if they both inject stuff directly into the window object of the same window they can collide. I have to prevent that at all cost, as I inject the extension object as well as the messenger object into the AddOns window scope and those must not be used by the wrong AddOn.

I will not change that in an API which is intended to be used by lots of developers. I cannot.

> But I want to put my XUL in XUL files.

I tried to support XUL files and the result was a support nightmare. So many edge cases, so many adjustments to the XUL, so many hours of dev time to get it working. Remember: There is no XUL overlay loader in TB78. The released WindowListener is my third API of that general concept and what I determined to be the most simple approach with the least amount of dev time. You must also not forget, that my overall upgrade concept does not end here but continues after the AddOn runs in TB78, to get the legacy pieces out.

That is why a few things are as they are:
* no XUL files
* single JavaScript files per window
* autogenerated namespace

**Comment by eyalroz** [comment]
Ok, no XUL files. s/in a XUL file/in a XUL-like text file/ . The point is I want to maintain as much of the structure of my extension as possible. Not having to use backtick templates, and being able to get this stuff from a file (or a chrome URI) is significant. Ok, so I'll need to cut out the headers myself. Fine. But still.

> I will not change that in an API which is intended to be used by lots of developers. I cannot.

1. If it were a million users, then maybe what you're saying makes sense. We're talking about about a couple hundred extensions which get uploaded to ATN anyway.
2. But you're not even evading the problem with your approach. Chrome URIs will still clash if extension short names are identical. 
3. Extension short names don't clash and haven't clashed for 20 years. Really, you're insisting a convoluted solution to a non-issue.

**Comment by eyalroz** [comment]
>  You must also not forget, that my overall upgrade concept does not end here but continues after the AddOn runs in TB78, to get the legacy pieces out.

That's a matter of perspective. I don't think of it as an "upgrade" process out of "legacy". I see your project as a loader for extensions to make them work with an unfortunately-crippled application.

**Comment by jobisoft** [comment]
> Ok, no XUL files. s/in a XUL file/in a XUL-like text file/ . The point is I want to maintain as much of the structure of my extension as possible. Not having to use backtick templates, and being able to get this stuff from a file (or a chrome URI) is significant. Ok, so I'll need to cut out the headers myself. Fine. But still.

You can try that, but you will fail due to the way the overlay loader worked. If you really want to not have to split up your XUL files in pieced, you have to write an overlayloader yourself. I would say "trust me" but it looks like you don't. But I still would like to save you from wasting time.

> But you're not even evading the problem with your approach. Chrome URIs will still clash if extension short names are identical.

The point is: I do not care. If the extension clashed before and no one noticed: fine. They can continue to do that.

But the new stuff I introduce must not. That is why I went for the autogenersted name. What is yours actual issue with the namespace?

What should I do, if the user does not or no longer needs to register a chrome Uri? What should I use them? When the user defined multiple chrome Uris, which should I use? All that and much more considerations led me to use this he autogenerated namespace.

**Comment by eyalroz** [comment]
> You can try that, but you will fail due to the way the overlay loader worked. If you really want to not have to split up your XUL files in pieces, you have to write an overlayloader yourself. I would say "trust me" but it looks like you don't. But I still would like to save you from wasting time.

1. You're mis-imagining what I'm hoping to achieve - although perhaps I described it in an overly grandiose way. Right now, with your method, I have to place pieces of XUL in the injector `.js` file. I would rather those same pieces just stay in their own file and be loaded as strings to feed into the ParseXULFragment.
2. If that can be achieved, and perhaps with some simple specification of scripts and such - it should be possible to auto-inject XUL fragments, CSS and JS into windows, without the extension author having to write their own injector.

> The point is: I do not care. If the extension clashed before and no one noticed: fine. They can continue to do that.

No... they didn't clash. They never clash. It doesn't happen... (and if it somehow does with somebody's private extension - then indeed you don't care).

> But the new stuff I introduce must not. 

Then just check if it already exists, and if it does - refuse to do anything and throw an exception.

> That is why I went for the autogenerated name. What is yours actual issue with the namespace?

It is an idiosyncrasy. Something that is not necessary, that the developer has to learn and memorize, and remember when debugging; it causes inconsistent behavior across runs; it forces the intrication of text (of sorts) and code; it makes auto-generation and preprocessing of code more difficult. Etc.

Oh, and - you're forgetting some clever people will just overwrite the namespace variable in the WindowListener code, since every extension bundles it independently. I'm sure you'll also have a fun time with different versions of WindowListener interacting in the same running TB instance, regardless of this fact...


> What should I do, if the user does not or no longer needs to register a chrome Uri? What should I use them? When the user defined multiple chrome Uris, which should I use? All that and much more considerations led me to use the autogenerated namespace.

That is actually a fair point. There are a few options which may be combined:

1. Define a new `manifest.json` key. Call it, say, `shortname`. Only accepted if it can be used as an identifier.
2. Have the `background.js` set the namespace with some WindowListener method.
3. Fall back on your auto-generated value if you no other name has been set.

**Comment by jobisoft** [comment]
A function to read chrome files from within the XPI:
https://github.com/jobisoft/EAS-4-TbSync/blob/master/content/includes/tools.js#L80

Using that you can have the xul pieces in files instead of backticks.

**Comment by jobisoft** [comment]
The function `WindowListener.startListening()` now accepts an optinal parameter, which will override the auto generated namespace. Add-on statup will be terminated, if a naming collision is detected. Update your API files to version 1.7.

I also added a helper function `injectCSS` to the add-on scope, which adds a css file to the window. That CSS will be automatically removed on window unload.

I tend to provide similar functions for addAfter() addBefore() and addTo().

**Comment by jobisoft** [comment]
Can I close this?

**Comment by eyalroz** [comment]
Yes, thank you. The `addAfter()` etc. changes are relevant to other issues, not this one...

**Comment by jobisoft** [comment]
I would like to ask you for a test. When you load scripts into your scope, you did

`Services.scriptloader.loadSubScript("chrome://removedupes/content/removedupes.js", this, "UTF-8");`

Can you do

`Services.scriptloader.loadSubScript("chrome://removedupes/content/removedupes.js", window, "UTF-8");`

instead? 

This will load your script directly into the window scope (you already use the RemoveDupes encapsulation, so no clash is to be expected). All file scope code will be executed in the window scope and you do not need to make changes to your XUL and your code.

The only thing is, your code is not directly reachable from the scope of the injected javascript file, but i do not see such calls. If you need to make such calls, like an init function, you must prepend "window." to that call and you may switch to the window scope by using `call()`. Instead of

`RemoveDupes.someFunction(var1, var2);`

do

`window.RemoveDupes.someFunction.call(window, var1, var2);`

This will execute the function in the window scope. If you just do this:

`window.RemoveDupes.someFunction(var1, var2);`

The function will be executed fine, but will only find your RemoveDupes object, if you prepend "window." everywhere. Also any standard function available in the window scope will not be found.

If that works than:
* the new stuff (messenger and extension objects) are only available in your protected scope and cannot clash with other add-ons
* Only a small set of calls (those in your injected script) need to be changed to use `call()`.
* XUL and imported files do not need to be changed.

**Comment by eyalroz** [comment]
I'll try this out (with the latest version of `implementation.js`). But just to be clear:

* Calls from JS code in the injector script <- Don't have any so never mind
* Calls from within the XUL fragment <- `window.RemoveDupes`
* Calls from within injected "subscript" <- `RemoveDupes`

Have I got that right?

**Comment by jobisoft** [comment]
If you load your subscripts into window, you can use RemoveDupes in your XUL and in the loaded subscripts, just as you would in the legacy extension. You only need window.RemoveDupes from within the injected script. 

But I will get rid of that as well tonight with v2.0

**Comment by eyalroz** [comment]
Ok, I tried this. A new (minor) issue is that some globals which, in the past, I could just define for myself, I now have to check for. Specifically, in my injected script (not the injector script), I have:
```
const Cc = Components.classes;
const Ci = Components.interfaces;
```
and now I get an error for them. But this is fine, I have no problem checking for them being defined already. Doing that now to continue the experiment.

**Comment by jobisoft** [comment]
I renamed `namespace` to `scopeName` and updated the wiki to show the two diferent JavaScript load concepts. Feedback is appreciated.

**Comment by eyalroz** [comment]
Well, I'm still of the opinion that a generated scope name is confusing (especially at run-time) and its use is bug-prone, and would recommend it not be used. So I'm not really the person to review this point... I'm glad that the guide tells you how to put things in the window scope, and would like suggested as the first alternative.

**Comment by jobisoft** [comment]
You no longer need to use the scopeName and I switched order of the two concepts in the guide.
