### ISSUE TITLE
What to do with platform-specific chrome.manifest?

### ISSUE THREAD

**Issue by eyalroz** [thundernest/addon-developer-support#9]
(Relates to #1 w.r.t. skins)

Regular XUL extension can have more than one main chrome.manifest file; specifically, they sometimes (often?) have additional, platform-specific `chrome.manifest`. (In my extension's case it's some additional CSS for MacOS which needs different URIs for the checked/unchecked symbols.)

1. The wiki should suggest how to account for these pieces of chrome.
2. You should consider automating this functionality by allowing registration of platform-specific entities which will only be used/loaded on the relevant platform .

The suggestion regarding what to do right now is probably having a platform check in the injector script example [here](https://github.com/thundernest/addon-developer-support/wiki/WindowListener-API:-JavaScript-Injection#onload).

**Comment by jobisoft** [comment]
You are correct, you have to take care of OS specific things in your injected JS. I will add an example using Services.appinfo.*

We must get away from automated checks in this first update step and return to pure JS solutions. You will see, that it is only an if clause in your JS instead of registerung a whole different JS file for Mac, Linux and Win in your background.js. You can still keep them independent and load only the needed JS in your registered injection script.

**Comment by jobisoft** [comment]
I added a note here:
https://github.com/thundernest/addon-developer-support/wiki/WindowListener-API:-Getting-Started#windowlistenerregisterwindow

Closing this to have it out of the way. Reopen if needed.
